
bash docker_files/docker_td3_plus_bc_single_model_next_model_0_noise_cheetah_vel_medium_random_1_1000.sh 1 0
bash docker_files/docker_td3_plus_bc_single_model_next_model_0_noise_cheetah_dir_medium_random_1_1000.sh 3 0
bash docker_files/docker_td3_plus_bc_single_model_next_model_0_noise_ant_dir_medium_random_1_1000.sh 3 0
bash docker_files/docker_td3_plus_bc_single_model_next_model_0_noise_walker_dir_medium_random_1_1000.sh 3 0
