from myd3rlpy.models.torch.q_functions.ensemble_q_function import EnsembleContinuousQFunctionWithTaskID, EnsembleDiscreteQFunctionWithTaskID
from myd3rlpy.models.torch.q_functions.qr_q_function import ContinuousQRQFunctionWithTaskID, DiscreteQRQFunctionWithTaskID
from myd3rlpy.models.torch.q_functions.fqf_q_function import ContinuousFQFQFunctionWithTaskID, DiscreteFQFQFunctionWithTaskID
from myd3rlpy.models.torch.q_functions.fqf_q_function import ContinuousFQFQFunctionWithTaskID, DiscreteFQFQFunctionWithTaskID
from myd3rlpy.models.torch.q_functions.mean_q_function import ContinuousMeanQFunctionWithTaskID, DiscreteMeanQFunctionWithTaskID
